### ISSUE TITLE
Server throws an error on instantiation of new demo app

### ISSUE THREAD

**Issue by andyburnett** [virtual-world-framework/vwf#474]
I have just installed an instance of VWF using the recommended install script.

vwf create 1world
cd 1world
vwf

Produces the following error
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at Object._404 (/root/.vwf/lib/nodejs/serve.js:41:18)
    at Object.Serve (/root/.vwf/lib/nodejs/vwf.js:143:15)
    at Server.OnRequest (/root/.vwf/node_vwf.js:106:17)
    at Manager.handleRequest (/root/.vwf/node_modules/socket.io/lib/manager.js:565:28)
    at Server.<anonymous> (/root/.vwf/node_modules/socket.io/lib/manager.js:119:10)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)

**Comment by andyburnett** [comment]
Scratch that. It turns out it was a conflict between two installed versions of Node.
