### ISSUE TITLE
vwf-apps

### ISSUE THREAD

**Issue by lazydino** [virtual-world-framework/vwf#537]
I can't seem to get some of the examples at https://github.com/virtual-world-framework/vwf-apps.git running. One particular sample is 'mulituser'.  This is what I got from the console:

C:\vwf>node . -a ..\vwf-apps
LogLevel = 1
Serving VWF support files from C:\vwf
Serving VWF applications from ..\vwf-apps
Serving on port 3000
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at Object._404 (C:\vwf\lib\nodejs\serve.js:41:18)
    at Object.Serve (C:\vwf\lib\nodejs\vwf.js:143:15)
    at Server.OnRequest (C:\vwf\node_vwf.js:106:17)
    at Manager.handleRequest (C:\vwf\node_modules\socket.io\lib\manager.js:565:28)
    at Server.<anonymous> (C:\vwf\node_modules\socket.io\lib\manager.js:119:10)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:528:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)

-----------------------------------------------------------------------------------------------
vwf and vwf-apps are cloned into my c:\vwf and c:\vwf-apps respectively. Any idea?

**Comment by scottnc27603** [comment]
That's not the right directory for the apps.  Try placing the contents into
c:\vwf\public

Scott

**Comment by lazydino** [comment]
Thanks! so the applicationPath link will not work for every app, I need to copy the repos to the public subfolder of vwf?

**Comment by scottnc27603** [comment]
The system is set up to run the apps from /public by default.  I know there
was a way to change that, but I never tried to run from any other location.

**Comment by eric79** [comment]
Hmm ... yeah the `-a` command line argument that @lazydino is using should be correct.  I wonder if it's having issues for some reason because the apps are not in a subfolder of `c:\vwf`.

@lazydino, could you try moving it under `c:\vwf` somewhere and see if it works there?  My only other idea is that somewhere in the server, it doesn't like the Windows-style `\` and is treating it as an escape character.  You could try making it a `/` and see if your results are any different.

**Comment by lazydino** [comment]
It is not a 'slash vs back slash' issue. I've tried '-a' on both linux and windows, the result is the same. Making vwf-apps located under vwf doesn't work for multiuser app either. 

Chaning application path via '-a' works for most of the applications like duck and humvee, but multiuser and plane won't be served under directory other than 'public'. Looks like something go wrong in one of the vwf components referenced....

**Comment by eric79** [comment]
Ah, interesting ... I wonder if those apps assume a particular relative path to a component.  I guess the answer for now is that those apps do indeed need to be served from `public`.

Thanks for finding that.
